vaxspace/vaxapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from vaxapp.views import overall_vaccination_graph


app_name = 'vaxapp'

urlpatterns = [
    path('', views.loginPage, name='loginPage'),
    path('user_register/', views.user_register, name='user_register'),
    path('index/', views.index, name='index'),
    path('update_admin/', views.update_admin, name='update_admin'),
    path('index/utilities/', views.utilities, name='utilities'),
    path('healthworker/', views.healthworker, name='healthworker'),
    path('update_healthworker/', views.update_healthworker, name='update_healthworker'),
    path('index/barangay/', views.barangay, name='barangay'),
    path('guardian/', views.guardian, name='guardian'),
    path('update_guardian/', views.update_guardian, name='update_guardian'),
    path('edit_guardian/<int:id>/', views.edit_guardian, name='edit_guardian'),
    path('edit_healthworker/<int:id>/', views.edit_healthworker, name='edit_healthworker'),
    path('edit_vaccine/<int:id>/', views.edit_vaccine, name='edit_vaccine'),
    path('edit_barangay/<int:id>/', views.edit_barangay, name='edit_barangay'),
    path('add_healthworker/', views.add_healthworker, name='add_healthworker'),
    path('index/add_vaccine/', views.add_vaccine, name='add_vaccine'),
    path('charts/', views.charts, name='charts'),
    path('tables/', views.tables, name='tables'),
    path('admin_tables/', views.admin_tables, name='admin_tables'),
    path('buttons/', views.buttons, name='buttons'),
    path('admin_tables/add_record/<int:id>/', views.add_record, name='admin_add_record'),
    path('tables/add_record/<int:id>/', views.add_record, name='add_record'), 
    path('view_record_staff/<int:id>/', views.view_record_staff, name='view_record_staff'),
    path('view_record/<int:id>/', views.view_record, name='view_record'),
    path('tables/confirmation/<int:id>/', views.confirmation, name='confirmation'),
    path('edit_schedule/<int:id>/', views.edit_schedule, name='edit_schedule'),
    path('remove_child/<int:id>/', views.remove_child, name='remove_child'),
    path('remove_sched/<int:id>/', views.remove_sched, name='remove_sched'),
    path('delete_child/<int:id>/', views.delete_child, name='delete_child'),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('delete_worker/<int:id>/', views.delete_worker, name='delete_worker'),
    path('delete_vaccine/<int:id>/', views.delete_vaccine, name='delete_vaccine'),
    path('delete_brgy/<int:id>/', views.delete_brgy, name='delete_brgy'),
    path('save_to_admin/', views.save_to_admin, name='save_to_admin'),
    path('logout/', views.logout, name='logout'),
    path('index/overall-vaccination/', views.overall_vaccination_graph, name='overall_vaccination_graph'),
]

vaxspace/vaxspace/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vaxapp.urls', namespace="vaxapp")),
]

vaxspace/vaxapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Register, Vaccine
from django import forms





class CreateUserForm(UserCreationForm):
    role = forms.CharField(max_length=100)
    address = forms.CharField(max_length=255)
    contact = forms.IntegerField()  # Change to IntegerField

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'role', 'address', 'contact']
         

vaxspace/vaxapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from contextlib import redirect_stderr
from http.client import HTTPResponse
from django.http import HttpResponse
from .models import *
from django.contrib.auth.models import User, auth
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from vaxapp import views
from django.contrib.auth.models import Group
from datetime import datetime, date, timedelta, time
from django.utils.timezone import localdate
from django.utils import timezone
import pytz
from .forms import CreateUserForm
from .decorators import unauthenticated_user, allowed_users, admin_only
from django.db.models import Count
import matplotlib.pyplot as plt
import base64
import io
import urllib
import plotly.graph_objs as go
import json
from django.db.models import Q
# Create your views here.

from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.groups.filter(name='admin').exists():
                login(request, user)
                return redirect('index/')

            elif user.groups.filter(name='healthworker').exists():
                login(request, user)
                return redirect('healthworker/')

            elif user.groups.filter(name='guardian').exists():
                login(request, user)
                return redirect('guardian/')

        else:
            messages.error(request, 'Invalid credentials.')
            return redirect('/')
                

    return render(request, 'vaxapp/login.html')

@login_required
def update_healthworker(request):
    user = request.user

    if request.method == 'POST':
        # Update user profile if form is submitted
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.username = request.POST.get('username')
        user.password = request.POST.get('password')
        user.email = request.POST.get('email')
        # Update other user fields similarly
        
        user.save()
        messages.success(request, 'Updated successfully')
        return redirect('/healthworker/')  # Replace with your success URL
    else:
        messages.error(request, 'Error updating.')
        return redirect('/healthworker/') 
    return render(request, 'healthworker.html', {'user': user})

@login_required
def update_admin(request):
    user = request.user

    if request.method == 'POST':
        # Update user profile if form is submitted
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.username = request.POST.get('username')
        user.password = request.POST.get('password')
        user.email = request.POST.get('email')
        # Update other user fields similarly
        
        user.save()
        messages.success(request, 'Admin updated successfully')
        return redirect('/index/')  # Replace with your success URL
    else:
        messages.error(request, 'Error updating.')
        return redirect('/index/') 
    return render(request, 'index.html', {'user': user})

def edit_guardian(request, id):
    guardian = get_object_or_404(User, id=id)
    
    if request.method == 'POST':
        guardian.first_name = request.POST.get('first_name')
        guardian.last_name = request.POST.get('last_name')
        guardian.username = request.POST.get('username')
        guardian.email = request.POST.get('email')
        guardian.is_active = request.POST.get('is_active')
        # Update other guardian fields similarly
        
        guardian.save()
        messages.success(request, 'User updated successfully')
        return redirect('/admin_tables/')  # Replace with your success URL
    else:
        messages.error(request, 'Error updating.')
        return redirect('/admin_tables/') 

def edit_healthworker(request, id):
    healthworker = get_object_or_404(User, id=id)
    
    if request.method == 'POST':
        healthworker.first_name = request.POST.get('first_name')
        healthworker.last_name = request.POST.get('last_name')
        healthworker.username = request.POST.get('username')
        healthworker.email = request.POST.get('email')
        healthworker.is_active = request.POST.get('is_active')
        # Update other guardian fields similarly
        
        healthworker.save()
        messages.success(request, 'Healthworker updated successfully')
        return redirect('/admin_tables/')  # Replace with your success URL
    else:
        messages.error(request, 'Error updating.')
        return redirect('/admin_tables/') 

def edit_vaccine(request, id):
    vaccine = get_object_or_404(Vaccine, id=id)
    
    if request.method == 'POST':
        vaccine.name = request.POST.get('name')
        vaccine.description = request.POST.get('description')
        vaccine.dose1 = request.POST.get('chk1')
        vaccine.dose2 = request.POST.get('chk2')
        vaccine.dose3 = request.POST.get('chk3')
        vaccine.recommended_age1 = request.POST.get('recommended_age1')
        vaccine.recommended_age2 = request.POST.get('recommended_age2')
        vaccine.recommended_age3 = request.POST.get('recommended_age3')
        if not vaccine.recommended_age1:
            vaccine.recommended_age1 = None
        if not vaccine.recommended_age2:
            vaccine.recommended_age2 = None
        if not vaccine.recommended_age3:
            vaccine.recommended_age3 = None

            vaccine.save()
            messages.success(request, 'Vaccine updated successfully')
            return redirect('/admin_tables/')  # Replace with your success URL
    else:
        messages.error(request, 'Error updating.')
        return redirect('/admin_tables/') 

def edit_barangay(request, id):
    if id:
        barangay = get_object_or_404(Barangay, id=id)
        
        if request.method == 'POST':
            healthworker_username = request.POST.get('healthworker')
            if healthworker_username:
                try:
                    assign_healthworker = User.objects.get(username=healthworker_username)
                    barangay.healthworker = assign_healthworker
                    barangay.save()
                    messages.success(request, 'Updated successfully')
                except User.DoesNotExist:
                    messages.error(request, 'User does not exist')
            else:
                # Set healthworker_id to NULL
                barangay.healthworker = None
                barangay.save()
                messages.success(request, 'Healthworker cleared successfully')
        else:
            messages.error(request, 'Invalid request method')

    else:
        messages.error(request, 'Empty ID received.')
    
    return redirect('/admin_tables/')

@login_required
def update_guardian(request):
    user = request.user

    if request.method == 'POST':
        # Update user profile if form is submitted
        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')
        user.username = request.POST.get('username')
        user.password = request.POST.get('password')
        user.email = request.POST.get('email')
        # Update other user fields similarly
        
        user.save()
        messages.success(request, 'Updated successfully')
        return redirect('/guardian/')  # Replace with your success URL
    else:
        messages.error(request, 'Error updating.')
        return redirect('/guardian/') 
    return render(request, 'guardian.html', {'user': user})

@allowed_users(allowed_roles=['admin', 'healthworker'])
@admin_only
def index(request):
    vaccine = Vaccine.objects.all()
    vax_count = vaccine.count()
    regs = Admin_record.objects.all()
    regs_count = regs.count()
    guardian = User.objects.filter(groups=3)
    user_count = guardian.count()
    healthworker = User.objects.filter(groups=2)
    worker_count = healthworker.count()
    barangay = Barangay.objects.all()
    bar_count = barangay.count()
    
    vaccine_types = [vaccine.name for vaccine in vaccine]
    
    vaccinated_records = Vaccine_record.objects.filter(remarks__icontains='Vaccinated')
    non_vaccinated_records = Vaccine_record.objects.exclude(remarks__icontains='Vaccinated')
    vaccinated_counts = [0] * len(vaccine_types)
    non_vaccinated_counts = [0] * len(vaccine_types)

    for record in vaccinated_records:
        # Get vaccine IDs from the record (assuming 'vax1', 'vax2', 'vax3' are fields in Vaccine_record)
        vaccine_ids = [record.vax1, record.vax2, record.vax3]

        for vaccine_id in vaccine_ids:
            if isinstance(vaccine_id, int):  # Check if the ID exists and is an integer
                # Fetch corresponding Vaccine record and get the vaccine name
                vaccine = Vaccine.objects.filter(id=vaccine_id).first()
                if vaccine and vaccine.name in vaccine_types:
                    index = vaccine_types.index(vaccine.name)
                    vaccinated_counts[index] += 1

    for record in non_vaccinated_records:
        vaccine_ids = [record.vax1, record.vax2, record.vax3]

        for vaccine_id in vaccine_ids:
            if isinstance(vaccine_id, int):  # Check if the ID exists and is an integer
                vaccine = Vaccine.objects.filter(id=vaccine_id).first()
                if vaccine and vaccine.name in vaccine_types:
                    index = vaccine_types.index(vaccine.name)
                    non_vaccinated_counts[index] += 1

    context = {

vaxspace/vaxapp/templates/vaxapp/add_healthworker.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row justify-content-center align-items-center">
                    <div class="col-lg-7">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4"><strong>CREATE AN ACCOUNT FOR HEALTHWORKER</strong></h1>
                            </div>
                            <form method="POST" class="user" style="text-align: center; color: black;" autocomplete="off">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-sm-6 mb-3 mb-sm-0">
                                        {{ form.first_name.label }} {{ form.first_name }}
                                        <ul class="errorlist">
                                            {% for error in form.first_name.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.last_name.label }} {{ form.last_name }}
                                        <ul class="errorlist">
                                            {% for error in form.last_name.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        {{ form.username.label }} {{ form.username }}
                                        <ul class="errorlist">
                                            {% for error in form.username.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.email.label }} {{ form.email }}
                                        <ul class="errorlist">
                                            {% for error in form.email.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        {{ form.password1.label }} {{ form.password1 }}
                                        <ul class="errorlist">
                                            {% for error in form.password1.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                    <div class="col-sm-6">
                                        {{ form.password2.label }} {{ form.password2 }}
                                        <ul class="errorlist">
                                            {% for error in form.password2.errors %}
                                                <li class="text-danger">{{ error }}</li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                <input type="submit" class="btn btn-warning btn-user btn-block" value="Add account">
                                <a class="btn btn-danger btn-user btn-block" href="{% url 'vaxapp:index' %}">GO BACK</a>
                            </form>
                            <hr>
                            <div class="text-center">
                                
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>

</body>

</html>

vaxspace/vaxapp/templates/vaxapp/barangay.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/vaxspace_logo.png' %}">


    <title>VAXSPACE</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %}"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">

        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-7 mx-auto">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4"><strong>ADD NEW BARANGAY</strong></h1>
                            </div>
                            <form method="POST" class="user" style="color: black;">
                                {% csrf_token %}
                                <div class="form-group row justify-content-center">
                                    <div class="col-sm-6">
                                        <div class="text-center mb-3">
                                            <label for="brgy_name">Barangay name:</label>
                                            <input type="text" id="brgy_name" name="name" placeholder="Add new barangay" required>
                                        </div>
                                        <div class="text-center">
                                            <label for="assign">Select health worker</label><br>
                                            <select id="assign" name="healthworker">
                                                <option value="{{ user.first_name }}">----------</option>
                                                {% for assign in assign_brgy %}
                                                <option>{{assign.first_name}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                
                                <div class="text-center"> 
                                    <a href="{% url 'vaxapp:index' %}" class="btn btn-danger">GO BACK</a>
                                    <input type="submit" class="btn btn-primary" value="Add barangay">
                                </div>
                            </form>
                            
                            <hr>
                        </div>
                    </div>
                </div>
                
                </div>
            </div>
        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>

</body>

</html>

vaxspace/vaxapp/templates/vaxapp/confirmation.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>VAXSPACE</title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="{% static 'https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i' %}"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/alert.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
    {% include 'vaxapp/messages.html' %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-7">
                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4"><strong>CONFIRM VACCINATION</strong></h1>
                            </div>
                            <form method="POST" class="user text-gray-900" style="text-align:center;background-color:#eeeeee;opacity:90%;border-radius:5px;padding:10px">
                                {% csrf_token %}
                                <div style="text-align:center" class="row">
                                    <div class="col">
                                        <input type="hidden" name="child_id" value="{{confirm.child.id}}">
                                        <input type="hidden" name="brgy" value="{{confirm.child.address.id}}">
                                        <input type="hidden" name="birthheight" value="{{confirm.child.birth_height}}">
                                        <input type="hidden" name="birthweight" value="{{confirm.child.birth_weight}}">
                                        <input type="hidden" name="vax1" value="{{confirm.vax1}}">
                                        <input type="hidden" name="vax1_info" value="{{confirm.vax1_info}}">
                                        <input type="hidden" name="vax2" value="{{confirm.vax2}}">
                                        <input type="hidden" name="vax2_info" value="{{confirm.vax2_info}}">
                                        <input type="hidden" name="vax3" value="{{confirm.vax3}}">
                                        <input type="hidden" name="vax3_info" value="{{confirm.vax3_info}}">
                                        <input type="hidden" name="vaxdate" value="{{confirm.vax_date}}">
                                        <input type="hidden" name="dob" value="{{confirm.date_of_birth}}">
                                        <h4>{{confirm.child}}</h4><sup>Child's Name</sup>
                                        <hr class="sidebar-divider d-none d-md-block">
                                        <h5>{{confirm.vax1_info}} {{confirm.vax2_info}} {{confirm.vax3_info}}</h5><sup>Vaccines & Doses</sup>
                                        <hr class="sidebar-divider d-none d-md-block">
                                        <h5>{{confirm.vax_date}}</h5><sup>Vaccination date</sup>
                                        <hr class="sidebar-divider d-none d-md-block">
                                        <input type="text" name="b_height" placeholder="Previous height:{{confirm.child.birth_height}}cm" required><br><sup>Birth height</sup><br>
                                        <input type="text" name="b_weight" placeholder="Previous height:{{confirm.child.birth_weight}}lbs" required><br><sup>Birth weight</sup>
                                        <hr class="sidebar-divider d-none d-md-block">
                                        <input type="text" name="vaccinator" placeholder="Name of Vaccinator" required><br><sup>Vaccinator</sup><br>
                                        <input type="text" name="remarks" placeholder="Ex: Vaccinated, Missed, etc." required><br><sup>Remarks</sup>
                                    </div>
                                </div>
                                <br>
                                <div class="text-center">
                                    <a href="{% url 'vaxapp:tables' %}" class="btn btn-danger">Cancel</a>
                                    <input type="submit" class="btn btn-success" value="Confirm">
                                </div>
                            </form>
                           
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

  

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

    <!-- Bootstrap's built-in JS for dismissing alerts with fade -->
<script src="{% static 'js/alert.js' %}"></script>

</body>

</html>

vaxspace/vaxapp/templates/vaxapp/messages.html
{% if messages %}
    {% for message in messages %}
    <div style="font-size: large; text-align:center" class="{{ message.tags }} s_alert" id="msg" role="alert">
        {{message}}
    </div>
    {% endfor %}

{% endif %}